#!/bin/bash
ATOM_PACKAGE=(
	atom-clock 
	platformio-ide-terminal 
	atom-beautify 
	file-icons 
	pigments 
	color-picker 
	atom-symfony2 
	highlight-selected 
	language-generic-config 
	php-twig 
	atom-typescript 
	react 
	autoclose-html
)